from tkinter import *
root=Tk()
root.title("login app")
root.geometry("400x400")
frame=Frame(master=root,height=200,width=300,bg="lightblue")
lbl1=Label(frame,text="full name",bg="white",fg="black",width=12)
lbl2=Label(frame,text="email",bg="white",fg="black",width=12)
lbl3=Label(frame,text="password",bg="white",fg="black",width=12)
name_entry=Entry(frame)
email_entry=Entry(frame)
password_entry=Entry(frame,show="*")
def display():
    name=name_entry.get()
    greet="welcome "+name 
    message="\n congrats tfor your new acount"
    textbox.insert(END,greet)
    textbox.insert(END,message)
btn=Button(text="create acount",bg="black",fg="white",command=display)
textbox=Text(height=5,width=30)
frame.place(x=20,y=0)
lbl1.place(x=20,y=20)
name_entry.place(x=150,y=20)
lbl2.place(x=20,y=80)
email_entry.place(x=150,y=80)
lbl3.place(x=20,y=140)
password_entry.place(x=150,y=140)
btn.place(x=130,y=210)
textbox.place(y=250)
root.mainloop()
